server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: user
    password: passw0rd
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: default

logging:
  level:
    root: INFO
